# Generated by tools/generate-locales.mjs. Do not edit by hand.

set(POLYCPP_MOMENT_AVAILABLE_LOCALES
    "af"
    "ar-dz"
    "ar-kw"
    "ar-ly"
    "ar-ma"
    "ar-ps"
    "ar-sa"
    "ar-tn"
    "ar"
    "az"
    "be"
    "bg"
    "bm"
    "bn-bd"
    "bn"
    "bo"
    "br"
    "bs"
    "ca"
    "cs"
    "cv"
    "cy"
    "da"
    "de-at"
    "de-ch"
    "de"
    "dv"
    "el"
    "en-au"
    "en-ca"
    "en-gb"
    "en-ie"
    "en-il"
    "en-in"
    "en-nz"
    "en-sg"
    "eo"
    "es-do"
    "es-mx"
    "es-us"
    "es"
    "et"
    "eu"
    "fa"
    "fi"
    "fil"
    "fo"
    "fr-ca"
    "fr-ch"
    "fr"
    "fy"
    "ga"
    "gd"
    "gl"
    "gom-deva"
    "gom-latn"
    "gu"
    "he"
    "hi"
    "hr"
    "hu"
    "hy-am"
    "id"
    "is"
    "it-ch"
    "it"
    "ja"
    "jv"
    "ka"
    "kk"
    "km"
    "kn"
    "ko"
    "ku-kmr"
    "ku"
    "ky"
    "lb"
    "lo"
    "lt"
    "lv"
    "me"
    "mi"
    "mk"
    "ml"
    "mn"
    "mr"
    "ms-my"
    "ms"
    "mt"
    "my"
    "nb"
    "ne"
    "nl-be"
    "nl"
    "nn"
    "oc-lnc"
    "pa-in"
    "pl"
    "pt-br"
    "pt"
    "ro"
    "ru"
    "sd"
    "se"
    "si"
    "sk"
    "sl"
    "sq"
    "sr-cyrl"
    "sr"
    "ss"
    "sv"
    "sw"
    "ta"
    "te"
    "tet"
    "tg"
    "th"
    "tk"
    "tl-ph"
    "tlh"
    "tr"
    "tzl"
    "tzm-latn"
    "tzm"
    "ug-cn"
    "uk"
    "ur"
    "uz-latn"
    "uz"
    "vi"
    "x-pseudo"
    "yo"
    "zh-cn"
    "zh-hk"
    "zh-mo"
    "zh-tw"
)

option(POLYCPP_MOMENT_ENABLE_ALL_LOCALES "Compile and register all generated Moment.js locales when POLYCPP_MOMENT_LOCALES is empty" ON)
set(POLYCPP_MOMENT_LOCALES "" CACHE STRING "Comma or semicolon separated Moment.js locale keys to compile/register; overrides POLYCPP_MOMENT_ENABLE_ALL_LOCALES when non-empty")
set_property(CACHE POLYCPP_MOMENT_LOCALES PROPERTY STRINGS ${POLYCPP_MOMENT_AVAILABLE_LOCALES})

function(polycpp_moment_configure_locales target)
    set(_requested "${POLYCPP_MOMENT_LOCALES}")
    string(REPLACE "," ";" _requested "${_requested}")
    string(REPLACE " " ";" _requested "${_requested}")

    set(_selected)
    if(_requested)
        foreach(_locale IN LISTS _requested)
            string(STRIP "${_locale}" _locale)
            if(_locale STREQUAL "")
                continue()
            endif()
            string(TOLOWER "${_locale}" _locale)
            if(_locale STREQUAL "all")
                list(APPEND _selected ${POLYCPP_MOMENT_AVAILABLE_LOCALES})
            elseif(_locale STREQUAL "none")
                set(_selected)
            else()
                list(FIND POLYCPP_MOMENT_AVAILABLE_LOCALES "${_locale}" _locale_index)
                if(_locale_index EQUAL -1)
                    message(FATAL_ERROR "Unknown Moment.js locale '${_locale}'. Valid locales: ${POLYCPP_MOMENT_AVAILABLE_LOCALES}")
                endif()
                list(APPEND _selected "${_locale}")
            endif()
        endforeach()
    elseif(POLYCPP_MOMENT_ENABLE_ALL_LOCALES)
        set(_selected ${POLYCPP_MOMENT_AVAILABLE_LOCALES})
    endif()

    if(_selected)
        list(REMOVE_DUPLICATES _selected)
    endif()

    list(LENGTH POLYCPP_MOMENT_AVAILABLE_LOCALES _available_count)
    list(LENGTH _selected _selected_count)
    set(_all_enabled FALSE)
    if(_selected_count EQUAL _available_count)
        set(_all_enabled TRUE)
    endif()

    set(POLYCPP_MOMENT_SELECTED_LOCALES "${_selected}" PARENT_SCOPE)
    set(POLYCPP_MOMENT_ALL_GENERATED_LOCALES_ENABLED "${_all_enabled}" PARENT_SCOPE)

    if(_selected)
        target_sources(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src/generated_locales.cpp")
        foreach(_locale IN LISTS _selected)
            string(MAKE_C_IDENTIFIER "${_locale}" _locale_ident)
            target_compile_definitions(${target} PRIVATE "POLYCPP_MOMENT_LOCALE_${_locale_ident}")
        endforeach()
        message(STATUS "polycpp_moment generated locales: ${_selected_count} enabled")
    else()
        target_compile_definitions(${target} PUBLIC POLYCPP_MOMENT_DISABLE_GENERATED_LOCALES)
        message(STATUS "polycpp_moment generated locales: disabled")
    endif()
endfunction()
